"""Build CSS and documentation metadata from the canonical JSON token file."""
import json
import re
from pathlib import Path

root = Path(__file__).resolve().parents[1]
source = json.loads((root / 'assets/design-system/tokens.json').read_text(encoding='utf-8'))
tokens = [t for group in source['groups'] for t in group['tokens']]
names = [t['name'] for t in tokens]
if len(names) != len(set(names)):
    raise ValueError('Duplicate token name')
by_name = {t['name']: t for t in tokens}
def dependencies(name, seen=()):
    if name in seen:
        raise ValueError('Cyclic token: ' + name)
    if name not in by_name:
        raise ValueError('Missing token: ' + name)
    t = by_name[name]
    refs = set(re.findall(r'var\((--[\w-]+)', t['value'] + t.get('dark', '')))
    return refs | {ref for child in refs for ref in dependencies(child, (*seen, name))}
theme_values = {t['name'] for t in tokens if t.get('dark', t['value']) != t['value']}
# Alias values are computed at their declaration element. Rebind every transitive
# theme-dependent alias at BOTH boundaries, including light nested inside dark.
theme_names = theme_values | {t['name'] for t in tokens if dependencies(t['name']) & theme_values}
css = ['/* Generated by scripts/build-design-tokens.py. Edit tokens.json. */', ':root {']
for group in source['groups']:
    css.append(f"  /* {group['title']} */")
    css.extend(f"  {t['name']}: {t['value']};" for t in group['tokens'])
css.append('}')
for theme in ['light', 'dark']:
    css.append(f'[data-ds-theme="{theme}"] {{')
    css.append(f'  color-scheme: {theme};')
    css.append('  color: var(--semantic-label-normal);')
    css.extend(f"  {t['name']}: {t.get('dark', t['value']) if theme == 'dark' else t['value']};" for t in tokens if t['name'] in theme_names)
    css.append('}')
for t in tokens:
    if t['name'].startswith('--type-') and t['name'].endswith('-size'):
        name=t['name'][7:-5]
        css.append(f'.type-{name} {{ font-size:var(--type-{name}-size); line-height:var(--type-{name}-line); letter-spacing:var(--type-{name}-tracking); }}')
(root / 'assets/css/tokens.css').write_text('\n'.join(css)+'\n',encoding='utf-8')
(root / 'assets/js/design-system/tokens.js').write_text('/* Generated. */\nexport const tokenGroups = '+json.dumps(source['groups'],ensure_ascii=False,indent=2)+';\n',encoding='utf-8')
print(f'Built {len(tokens)} tokens in {len(source["groups"])} groups.')
